<?php

use Illuminate\Database\Seeder;

class EntryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('entry')->delete();
    	DB::table('entry')->insert([
    		'title'=>'title 1',
			'content'=>'
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et eros in nisi placerat ultricies eu id magna. Mauris non dolor eget sapien congue hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin odio odio, tincidunt id suscipit id, vulputate vitae sapien. Quisque placerat velit vitae massa convallis, non vestibulum tellus faucibus. Nunc finibus et magna id volutpat. Cras posuere rutrum tortor non sagittis. Cras vel pulvinar velit. Donec mattis dignissim porta.Fusce non mi lorem. Nunc consectetur nibh ut mi maximus, eget pellentesque quam rhoncus. Curabitur ac dolor eu nisl tincidunt luctus sed in dolor. Donec tincidunt nunc turpis, nec egestas mauris venenatis et. Fusce eu risus eu nisi suscipit tincidunt. Suspendisse vestibulum pharetra tortor vel blandit. Cras et nunc magna. Mauris condimentum eget velit non iaculis. In hac habitasse platea dictumst. Vivamus eget nunc id eros sollicitudin iaculis in quis odio. Sed efficitur purus et porttitor vestibulum. Fusce tincidunt ullamcorper volutpat.Vestibulum non consectetur dolor. Vestibulum dui nisi, accumsan sit amet metus et, vestibulum consectetur nisi. Sed scelerisque sodales urna, a egestas nisi congue vitae. Cras tempor velit est, eu vestibulum risus porta vel. Etiam finibus mauris vitae ipsum semper, sit amet placerat turpis consequat. Integer tempus ultrices lacus in vehicula. Quisque vitae nunc semper, venenatis nisl ac, porta lorem. Donec maximus diam sed enim interdum fermentum. Mauris auctor purus et eleifend aliquam. Vestibulum ultrices nunc nisi, tristique accumsan leo aliquet non. Etiam ullamcorper vestibulum erat, ac bibendum lacus commodo ac. Nam tempor orci non tellus vestibulum volutpat. Cras consectetur vestibulum massa, a blandit ante eleifend in.Curabitur ut turpis scelerisque, porttitor nisi eget, elementum nisi. Mauris id facilisis massa, sit amet facilisis massa. Nam enim magna, pellentesque vitae tempus quis, varius vitae ante. Phasellus finibus, tortor id semper mattis, justo est malesuada libero, in blandit sem risus vitae erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed laoreet orci mi, quis eleifend est convallis ut. Duis ac pretium ex.Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce euismod justo et tempor mattis. Proin sed dictum eros. Vivamus tempor tellus a gravida consectetur. Quisque at metus feugiat, viverra neque quis, aliquet neque. Proin odio eros, aliquet non lectus non, rhoncus porta leo. Cras nulla diam, faucibus id eros eu, semper blandit libero. Praesent dignissim est quis posuere tincidunt. ',
			'user_id'=>1,
			'image'=>'https://s3-us-west-2.amazonaws.com/uw-s3-cdn/wp-content/uploads/sites/6/2017/11/04133712/waterfall.jpg',
            'created_at'=>date('Y-m-d H:i:s')
    	]);
    	DB::table('entry')->insert([
    		'title'=>'title 2',
			'content'=>'
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et eros in nisi placerat ultricies eu id magna. Mauris non dolor eget sapien congue hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin odio odio, tincidunt id suscipit id, vulputate vitae sapien. Quisque placerat velit vitae massa convallis, non vestibulum tellus faucibus. Nunc finibus et magna id volutpat. Cras posuere rutrum tortor non sagittis. Cras vel pulvinar velit. Donec mattis dignissim porta.Fusce non mi lorem. Nunc consectetur nibh ut mi maximus, eget pellentesque quam rhoncus. Curabitur ac dolor eu nisl tincidunt luctus sed in dolor. Donec tincidunt nunc turpis, nec egestas mauris venenatis et. Fusce eu risus eu nisi suscipit tincidunt. Suspendisse vestibulum pharetra tortor vel blandit. Cras et nunc magna. Mauris condimentum eget velit non iaculis. In hac habitasse platea dictumst. Vivamus eget nunc id eros sollicitudin iaculis in quis odio. Sed efficitur purus et porttitor vestibulum. Fusce tincidunt ullamcorper volutpat.Vestibulum non consectetur dolor. Vestibulum dui nisi, accumsan sit amet metus et, vestibulum consectetur nisi. Sed scelerisque sodales urna, a egestas nisi congue vitae. Cras tempor velit est, eu vestibulum risus porta vel. Etiam finibus mauris vitae ipsum semper, sit amet placerat turpis consequat. Integer tempus ultrices lacus in vehicula. Quisque vitae nunc semper, venenatis nisl ac, porta lorem. Donec maximus diam sed enim interdum fermentum. Mauris auctor purus et eleifend aliquam. Vestibulum ultrices nunc nisi, tristique accumsan leo aliquet non. Etiam ullamcorper vestibulum erat, ac bibendum lacus commodo ac. Nam tempor orci non tellus vestibulum volutpat. Cras consectetur vestibulum massa, a blandit ante eleifend in.Curabitur ut turpis scelerisque, porttitor nisi eget, elementum nisi. Mauris id facilisis massa, sit amet facilisis massa. Nam enim magna, pellentesque vitae tempus quis, varius vitae ante. Phasellus finibus, tortor id semper mattis, justo est malesuada libero, in blandit sem risus vitae erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed laoreet orci mi, quis eleifend est convallis ut. Duis ac pretium ex.Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce euismod justo et tempor mattis. Proin sed dictum eros. Vivamus tempor tellus a gravida consectetur. Quisque at metus feugiat, viverra neque quis, aliquet neque. Proin odio eros, aliquet non lectus non, rhoncus porta leo. Cras nulla diam, faucibus id eros eu, semper blandit libero. Praesent dignissim est quis posuere tincidunt. ',
			'user_id'=>1,
			'image'=>'https://s3-us-west-2.amazonaws.com/uw-s3-cdn/wp-content/uploads/sites/6/2017/11/04133712/waterfall.jpg',
            'created_at'=>date('Y-m-d H:i:s')
    	]);
    	DB::table('entry')->insert([
    		'title'=>'title 3',
			'content'=>'
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et eros in nisi placerat ultricies eu id magna. Mauris non dolor eget sapien congue hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin odio odio, tincidunt id suscipit id, vulputate vitae sapien. Quisque placerat velit vitae massa convallis, non vestibulum tellus faucibus. Nunc finibus et magna id volutpat. Cras posuere rutrum tortor non sagittis. Cras vel pulvinar velit. Donec mattis dignissim porta.Fusce non mi lorem. Nunc consectetur nibh ut mi maximus, eget pellentesque quam rhoncus. Curabitur ac dolor eu nisl tincidunt luctus sed in dolor. Donec tincidunt nunc turpis, nec egestas mauris venenatis et. Fusce eu risus eu nisi suscipit tincidunt. Suspendisse vestibulum pharetra tortor vel blandit. Cras et nunc magna. Mauris condimentum eget velit non iaculis. In hac habitasse platea dictumst. Vivamus eget nunc id eros sollicitudin iaculis in quis odio. Sed efficitur purus et porttitor vestibulum. Fusce tincidunt ullamcorper volutpat.Vestibulum non consectetur dolor. Vestibulum dui nisi, accumsan sit amet metus et, vestibulum consectetur nisi. Sed scelerisque sodales urna, a egestas nisi congue vitae. Cras tempor velit est, eu vestibulum risus porta vel. Etiam finibus mauris vitae ipsum semper, sit amet placerat turpis consequat. Integer tempus ultrices lacus in vehicula. Quisque vitae nunc semper, venenatis nisl ac, porta lorem. Donec maximus diam sed enim interdum fermentum. Mauris auctor purus et eleifend aliquam. Vestibulum ultrices nunc nisi, tristique accumsan leo aliquet non. Etiam ullamcorper vestibulum erat, ac bibendum lacus commodo ac. Nam tempor orci non tellus vestibulum volutpat. Cras consectetur vestibulum massa, a blandit ante eleifend in.Curabitur ut turpis scelerisque, porttitor nisi eget, elementum nisi. Mauris id facilisis massa, sit amet facilisis massa. Nam enim magna, pellentesque vitae tempus quis, varius vitae ante. Phasellus finibus, tortor id semper mattis, justo est malesuada libero, in blandit sem risus vitae erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed laoreet orci mi, quis eleifend est convallis ut. Duis ac pretium ex.Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce euismod justo et tempor mattis. Proin sed dictum eros. Vivamus tempor tellus a gravida consectetur. Quisque at metus feugiat, viverra neque quis, aliquet neque. Proin odio eros, aliquet non lectus non, rhoncus porta leo. Cras nulla diam, faucibus id eros eu, semper blandit libero. Praesent dignissim est quis posuere tincidunt. ',
			'user_id'=>2,
			'image'=>'https://s3-us-west-2.amazonaws.com/uw-s3-cdn/wp-content/uploads/sites/6/2017/11/04133712/waterfall.jpg',
            'created_at'=>date('Y-m-d H:i:s')
    	]);
    }
}
